<a href="https://colab.research.google.com/github/J-cuerora/SE-ALES-Y-SISTEMAS/blob/main/ejercicios_de_sustentacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DICCIONARIO**

In [ ]:
mi_diccionario = {"nombre": "Juan","edad": 30,"ciudad": "Madrid"}

print(mi_diccionario)
print(mi_diccionario["ciudad"])

{'nombre': 'Juan', 'edad': 30, 'ciudad': 'Madrid'}
Madrid


In [ ]:
Datos={"nombre": "Ronaldinho", "edad": 45, "ciudad": "porto alegre,brasil", "hijo": "jao mendez" }
print(Datos)
print(Datos["ciudad"])

{'nombre': 'Ronaldinho', 'edad': 45, 'ciudad': 'porto alegre,brasil', 'hijo': 'jao mendez'}
porto alegre,brasil


In [ ]:
d={"a":10, "b": 20, "c": 30}
d["s"]=50 #Agregar al diccionario
print(d)
print(d["s"])

{'a': 10, 'b': 20, 'c': 30, 's': 50}
50


# CONTADOR **WHILE**


In [ ]:
A=4
while A <= 7:
  print(A)
  A+=1

4
5
6
7


# CONTADOR **FOR**

In [ ]:
for i in range(0,15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


# LISTA CICLO **FOR**

In [ ]:
# Lista original
lista = [1, "andres", 8, 9, 2]

# Lista vacía donde guardaremos los elementos invertidos
invertida = []

# Ciclo for recorriendo la lista de atrás hacia adelante
for i in range(len(lista) - 1, -1, -1):
    invertida.append(lista[i])

print("Lista original:", lista)
print("Lista invertida:", invertida)


Lista original: [1, 'andres', 8, 9, 2]
Lista invertida: [2, 9, 8, 'andres', 1]


In [ ]:
lista = [22, "Julian cuero", 19, 24, 25]
invertida =[]
for i in range(len(lista)-1,-1,-1):
  invertida.append(lista[i])
print("lista invertida",invertida)
print("lista original",lista)

lista invertida [25, 24, 19, 'Julian cuero', 22]
lista original [22, 'Julian cuero', 19, 24, 25]


# **LISTA CICLO WHILE**

In [ ]:
lista = [1, "andres", 8, 9, 2]
invertida = []
i = len(lista)-1
while i >= 0:
    invertida.append(lista[i])
    i -= 1
print("Lista original:", lista)
print("Lista invertida:", invertida)

Lista original: [1, 'andres', 8, 9, 2]
Lista invertida: [2, 9, 8, 'andres', 1]


In [ ]:
lista = [22," jugador", 19, "camila", "andres", 48]
invertida = []
i= len(lista)-1
while i>= 0 :
  invertida.append(lista[i])
  i-= 1
print("lista invertida", invertida)
print("lista original", lista)


lista invertida [48, 'andres', 'camila', 19, ' jugador', 22]
lista original [22, ' jugador', 19, 'camila', 'andres', 48]


# **VECTOR DE TIEMPO**

In [ ]:
import numpy as np
t=np.arange(10,15,1/50)

# **MATRICES**

In [ ]:
import numpy as NP
A= NP.array([[1,2,3],[4,5,6],[7,8,9]])
invertida = []# Corrected: Initialize as an empty Python list
for i in range(len(A)-1,-1,-1):
    invertida.append(A[i])
print(invertida)
print(A)

[array([7, 8, 9]), array([4, 5, 6]), array([1, 2, 3])]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#FILAS
import numpy as NP
A= NP.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])

[1 2 3]


In [ ]:
#COLUMNAS
import numpy as NP
A= NP.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[:,0])

[1 4 7]


In [ ]:
#ELEMENTO INDIVIDUAL
import numpy as NP
A= NP.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[2,1])

8


# **INDEXAR**

In [ ]:
import numpy as np
x=np.array([10,20,30,40,50,60,70,80])
x[0]
x[0]

np.int64(30)

# REPASO DE CLASES

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        return f"Hola, mi nombre es {self.nombre} y tengo {self.edad} años."

# Crear objeto
persona1 = Persona("Ana", 25)

# Usar métodos
print(persona1.saludar())

Hola, mi nombre es Ana y tengo 25 años.


# CLASES HERENCIA

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def describir(self):
        return f"{self.nombre}, {self.edad} años"


# Clase hija que hereda de Persona
class Estudiante(Persona):
    def __init__(self, nombre, edad, carrera):
      super().__init__(nombre, edad)
      self.carrera = carrera

    def describir_estudiante(self):
        return f"{self.describir()} - Estudia {self.carrera}"


# Crear objeto de la clase hija
estudiante1 = Estudiante("Luis", 20, "Ingeniería")

print(estudiante1.describir_estudiante())


Luis, 20 años - Estudia Ingeniería


In [ ]:
class Animal:
    def sonido(self):
        return "Sonido genérico"

class Perro(Animal):
    def sonido(self):
        return "Guau guau"  # Sobrescritura del método

class Gato(Animal):
    def sonido(self):
        return "Miau"

# Probar
animal = Animal()
perro = Perro()
gato = Gato()

print(animal.sonido())
print(perro.sonido())
print(gato.sonido())


Sonido genérico
Guau guau
Miau
